// dummy data
export const blogs = [
  { title: "Understanding JavaScript", category: "Technology", content: "Learn the basics of JavaScript, including variables, data types, and functions." },
  { title: "Healthy Living Tips", category: "Lifestyle", content: "Learn about healthy living habits including diet, exercise, and mental well-being." },
  { title: "How to Learn React", category: "Education", content: "Beginner's guide to React.js, covering JSX, components, and state management." },
  { title: "Tech Trends 2024", category: "Technology", content: "Explore the latest technology trends for 2024, including AI, quantum computing, and 5G." },
  { title: "Meditation Benefits", category: "Lifestyle", content: "The benefits of daily meditation on mental health and stress reduction." },
  { title: "Introduction to Node.js", category: "Technology", content: "An overview of Node.js, its use cases, and how to get started with building server-side applications." },
  { title: "Yoga for Beginners", category: "Lifestyle", content: "A guide to starting yoga, including beginner poses and tips for flexibility and strength." },
  { title: "Web Development Best Practices", category: "Education", content: "Best practices in web development, including clean code, performance optimization, and user experience." },
  { title: "Latest AI Innovations", category: "Technology", content: "A look at the latest breakthroughs in artificial intelligence and how they’re shaping various industries." },
  { title: "Mental Health Awareness", category: "Lifestyle", content: "Raising awareness about mental health issues and tips on how to manage stress and anxiety." },
  { title: "Becoming a Full Stack Developer", category: "Education", content: "Step-by-step guide to becoming a full-stack developer, including the skills needed for both frontend and backend." },
  { title: "Top 10 Coding Languages", category: "Technology", content: "Exploring the top 10 coding languages to learn in 2024." },
  { title: "Healthy Eating for Beginners", category: "Lifestyle", content: "Easy tips for adopting a healthier diet, with simple meal ideas and advice." },
  { title: "Building Your First App with React", category: "Education", content: "A beginner’s guide to building your first web app using React." },
  { title: "The Future of Cloud Computing", category: "Technology", content: "What to expect from the future of cloud computing and how it will affect businesses and users." },
  { title: "Managing Stress in a Busy World", category: "Lifestyle", content: "Effective techniques for managing stress in today’s fast-paced world." },
  { title: "Advanced JavaScript Techniques", category: "Technology", content: "Deep dive into advanced JavaScript techniques for improving your coding skills." },
  { title: "Fitness Goals for the New Year", category: "Lifestyle", content: "How to set realistic fitness goals and stick to them throughout the year." },
  { title: "React Hooks Explained", category: "Education", content: "Learn about React hooks, including `useState`, `useEffect`, and custom hooks." },
  { title: "Cybersecurity 101", category: "Technology", content: "An introduction to the basics of cybersecurity, protecting your data online." },
  { title: "Work-Life Balance Tips", category: "Lifestyle", content: "Practical tips for achieving a better work-life balance." },
  { title: "Why Learn TypeScript?", category: "Education", content: "Reasons why TypeScript is becoming increasingly popular among developers." },
  { title: "The Power of Responsive Design", category: "Technology", content: "Why responsive design is essential for modern websites and apps." },
  { title: "Building Strong Relationships at Work", category: "Lifestyle", content: "Tips for building meaningful relationships in your professional life." },
  { title: "Vue.js vs React: Which is Better?", category: "Technology", content: "Comparing Vue.js and React, and understanding the strengths of each framework." },
  { title: "The Importance of Hydration", category: "Lifestyle", content: "Why staying hydrated is crucial for your health and how to make it a habit." },
  { title: "The Rise of Edge Computing", category: "Technology", content: "Exploring edge computing and how it is transforming data processing." },
  { title: "How to Manage Personal Finances", category: "Lifestyle", content: "Learn how to budget, save, and invest wisely to improve your financial health." },
  { title: "Learning Data Structures and Algorithms", category: "Education", content: "A guide to understanding data structures and algorithms, crucial for coding interviews." },
  { title: "The Future of 5G Technology", category: "Technology", content: "How 5G will change the internet, mobile communications, and IoT." },
  { title: "Creating a Sustainable Home", category: "Lifestyle", content: "How to make your home more eco-friendly with simple sustainable practices." },
  { title: "Agile vs Waterfall: Which Methodology to Choose?", category: "Education", content: "Comparing Agile and Waterfall methodologies and when to use each in project management." },
  { title: "The Impact of Social Media on Mental Health", category: "Lifestyle", content: "How social media affects mental health and ways to manage its impact." },
  { title: "Building a Web Application with Express.js", category: "Education", content: "Learn how to create a full-stack web application using Express.js." },
  { title: "Cloud Storage Solutions for 2024", category: "Technology", content: "Explore the best cloud storage services available in 2024." },
  { title: "Meditation for Focus and Productivity", category: "Lifestyle", content: "How meditation can improve focus and productivity in your daily life." },
  { title: "Introduction to Machine Learning", category: "Technology", content: "A beginner's guide to machine learning, its applications, and how to get started." },
  { title: "Starting Your Own Blog", category: "Education", content: "A step-by-step guide on how to start your own blog and grow an audience." },
];
